name: Unit and Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run prittier
        run: npm run prettier:check
      - name: Check TypeScript
        run: npm run lint:quiet
      - name: Run e2e tests
        run: npm run cypress:run
